//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftShop.core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int IdShoppingCart { get; set; }
        public string userid { get; set; }
        public string IdProduct { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
