//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftShop.core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart
    {
        public string IdShopping { get; set; }
        public string user { get; set; }
        public string IdProduct { get; set; }
        public Nullable<bool> TransactionCompleted { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User1 { get; set; }
    }
}
